# Usa una imagen base ligera de Node
FROM node:18-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos del proyecto al contenedor
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código fuente
COPY . .

# Expone el puerto en el que corre tu servidor Express
EXPOSE 3001

# Comando para iniciar el servidor
CMD ["npm", "start"]